### ISSUE TITLE
Do you know what happened to opus_flutter?

### ISSUE THREAD

**Issue by jeffmikels** [EPNW/opus_dart#1]
The package opus_flutter appears to have been removed from pub.dev. Do you know where it went?

**Comment by EPNW** [comment]
It was actually never listed on pub (nor GitHub), due to Covid19 we werent able to do enough testing yet... I can post the current code on GitHub tomorrow I think...

**Comment by jeffmikels** [comment]
That would be awesome!

**Comment by EPNW** [comment]
Little update: I will take until tomorrow 😅

**Comment by EPNW** [comment]
As promised, you can find the current code of opus_flutter [here](https://github.com/EPNW/opus_flutter.git).

We testet a bit and it seems to work well enough, altrough we are not quit satisfied with the steps a user of the plugin needs to follow to integrate it into iOS. The problem here is that we don't want to include binaries (like a .lib or .framework) in the package itselfe (as this is against pub's best practice and open source culture), so the lack of a powerful automated build system (like gradle on Android) forces the user to do some work manually. Maybe you know a better way here. Feedback on how comprehensible the current instructions are is highly appreciated.

Speeking of Android: If you know a thing or two about the build system there, feel free to review to `Android.mk` since there might be optimizations we overlooked.

I'll leave this issue open until opus_flutter gets published to pub.

**Comment by jeffmikels** [comment]
Thanks!!

**Comment by jeffmikels** [comment]
Are you working on a mumble library? I am too.

**Comment by EPNW** [comment]
Yes.
It is already quite feature complete. The only thing not implemented is ACLs.
We planed to release it after completing it, but the current state of dumble (as we named the client), is sufficient for our current internal project.
So the priotity for completing (implementing acl and documenting) it is currently quite low.

**Comment by EPNW** [comment]
opus_flutter ist now in Pub so I'm closing this
