### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by MichealReed** [EPNW/opus_dart#2]
Any plans to support web? Here is a good javascript library that interfaces with the same C library via web assembly.

https://github.com/AnthumChris/opus-stream-decoder

**Comment by EPNW** [comment]
No, there are currently no plans to support web.
AFAIK dart can not bind against web assembly directly, so you would have to use dart:js as a mediator.
If the opus C API could be translated to js it would easy to port opus_dart, since only a few methods are actually used for the dart encoder/decoder.

**Comment by MichealReed** [comment]
The linked library above interfaces the web assembly via JS, dart:wasm will eventually bind directly, but for now you are correct, other libraries have used dart:js to accomplish this.

**Comment by EPNW** [comment]
We are currently discussing web support, I know it's been a while since you opend that issue, but may I ask you if you wanted to use opus_dart on the web with or without flutter?

**Comment by EPNW** [comment]
There is now web support using [`web_ffi`](https://pub.dev/packages/web_ffi).
